export const BookingActionType = {
  // SET_BOOKING: 'SET_BOOKING',
  TOGGLE_PEOPLE_MODAL_HIDDEN: 'TOGGLE_PEOPLE_MODAL_HIDDEN',
  PLUS_ADULT_GUEST: 'PLUS_ADULT_GUEST',
  MINUS_ADULT_GUEST: 'MINUS_ADULT_GUEST',
  PLUS_CHILD_GUEST: 'PLUS_CHILD_GUEST',
  MINUS_CHILD_GUEST: 'MINUS_CHILD_GUEST',
  PLUS_INFANT_GUEST: 'PLUS_INFANT_GUEST',
  MINUS_INFANT_GUEST: 'MINUS_INFANT_GUEST',
  TOTAL_GUEST: 'TOTAL_GUEST',
};
